"use client";
import React from "react";
import { Card, CardContent } from "@/components/ui/card";
import ChallengeCard from "@/components/ClimateChat/ChallengeCard"
import { Challenge } from "@/types";
import Markdown from "react-markdown";

/**
 * LLMResponseMessage Component
 *
 * This component renders a summary message generated by an AI model
 * and a list of related challenges using ChallengeCard components.
 *
 * @param {string} summary - AI-generated summary message
 * @param {Challenge[]} challenges - List of challenges related to the response
 */
export default function LLMResponseMessage({
  summary,
  challenges,
  onChallengeSelect, // Add this prop
}: {
  summary: string;
  challenges: Challenge[];
  onChallengeSelect: (challenge: Challenge) => void; // Callback function
}) {
  return (
    <div className="mb-4 text-left">
      {/* Main Card displaying the AI-generated response */}
      <Card className="inline-block max-w-2xl border-green-200 mx-auto text-center bg-green-100">
        <CardContent className="p-6">
          {/* Summary text with styling */}
          <div className="text-green-800 break-words text-left mb-4 prose prose-green">
            <Markdown>{summary}</Markdown>
          </div>
          {/* List of challenge cards (Handles case where challenges might be empty) */}
          <div className="grid gap-4">
            {challenges?.map((challenge) => (
              <ChallengeCard 
                challenge={challenge} 
                key={challenge.id} 
                onClick={() => onChallengeSelect(challenge)}
              />
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
