"use client";
import React from "react";
import { Card, CardContent } from "@/components/ui/card";
import ChallengeCard from "./ChallengeCard";
import { Challenge } from "@/types";

/**
 * LLMResponseMessage Component
 * 
 * This component renders a summary message generated by an AI model
 * and a list of related challenges using ChallengeCard components.
 * 
 * @param {string} summary - AI-generated summary message
 * @param {Challenge[]} challenges - List of challenges related to the response
 */
export default function LLMResponseMessage({
  summary,
  challenges,
}: {
  summary: string;
  challenges: Challenge[];
}) {
  return (
    <div className="mb-4 text-left">
      {/* Main Card displaying the AI-generated response */}
      <Card className="inline-block max-w-2xl border-green-200 mx-auto text-center">
        <CardContent className="p-6">
          {/* Summary text with styling */}
          <p className="text-lg font-semibold mb-4 text-green-800 break-words">
            {summary}
          </p>

          {/* List of challenge cards (Handles case where challenges might be empty) */}
          <div className="grid gap-4">
            {challenges?.map((challenge) => (
              <ChallengeCard challenge={challenge} key={challenge.id} />
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
